#!/bin/bash


<< help

This script takes a process/service as an argument and checks/monitors its status


help

read -p "what do you wish to do with your service $1: (status/pid)" choice

if [[ $choice == "status" ]];
then 
	sudo systemctl status $1
elif [[ $choice =="pid" ]];

then
	pgrep $1
else
	echo "wrong choice"
fi
